//! Adversarial audit, regression and performance tests for the static baked
//! lighting system (`src/lighting.rs` and the geometry it shades in
//! `src/render.rs`).
//!
//! These tests exist to break the lighting implementation, not merely to lock in
//! its happy path. They cover the pathological inputs a community level can
//! legitimately contain (huge rooms, dense fixture grids, overlapping rooms,
//! doorways, vertically offset props) as well as the malformed-but-parseable
//! ones, and they measure the level-build cost of representative levels on the
//! PocketCHIP-class budget (Mali-400/Lima, GLES2, ~512 MB).
//!
//! The benchmark half prints a compact table with
//! `cargo test --release -- --nocapture lighting_benchmark_report`.
//! Timings are informational; vertex counts, draw calls and budget arithmetic
//! are asserted so a regression fails the suite.

use std::time::Instant;

use crate::level::{LevelDef, MAX_LEVEL_PROP_VERTICES, MAX_LEVEL_VERTICES};
use crate::lighting::LevelLighting;
use crate::render::{
    LevelMesh, PropMeshBatch, build_level_geometry, build_level_geometry_with_assets,
};

// ---------------------------------------------------------------------------
// Level construction helpers
// ---------------------------------------------------------------------------

/// Minimal valid level JSON around a list of room definitions and light
/// entries, so each test can vary exactly one thing.
pub(crate) fn level_json(rooms_json: &str, lights_json: &str) -> String {
    format!(
        r#"{{
            "format_version": 1,
            "id": "audit",
            "name": "Audit",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{rooms_json}],
            "ceiling_lights": [{lights_json}]
        }}"#
    )
}

/// Parses level JSON, panicking with the parser error if the test's own JSON is
/// wrong (every string here is generated by the tests, not shipped data).
pub(crate) fn parse(json: &str) -> LevelDef {
    LevelDef::from_json(json).unwrap_or_else(|error| panic!("test level must parse: {error}"))
}

/// Shorthand for one ceiling light.
pub(crate) fn light(x: f32, z: f32, intensity: Option<f32>) -> String {
    match intensity {
        Some(value) => format!(
            r#"{{ "fixture": "core:fluorescent_panel_01", "x": {x}, "z": {z}, "intensity": {value} }}"#
        ),
        None => format!(r#"{{ "fixture": "core:fluorescent_panel_01", "x": {x}, "z": {z} }}"#),
    }
}

/// One room definition.
pub(crate) fn room(x: f32, z: f32, width: f32, depth: f32, height: f32) -> String {
    format!(r#"{{ "x": {x}, "z": {z}, "width": {width}, "depth": {depth}, "height": {height} }}"#)
}

/// A square room with `count` fixtures spread evenly over it.
pub(crate) fn square_room_level(
    size: f32,
    height: f32,
    count: usize,
    intensity: Option<f32>,
) -> LevelDef {
    let mut lights = Vec::with_capacity(count);
    let (cols, rows) = fixture_grid(count);
    for row in 0..rows {
        for col in 0..cols {
            if row * cols + col >= count {
                break;
            }
            let x = size * (col as f32 + 1.0) / (cols as f32 + 1.0);
            let z = size * (row as f32 + 1.0) / (rows as f32 + 1.0);
            lights.push(light(x, z, intensity));
        }
    }
    parse(&level_json(
        &room(0.0, 0.0, size, size, height),
        &lights.join(","),
    ))
}

/// Grid shape for `count` roughly evenly spaced fixtures.
fn fixture_grid(count: usize) -> (usize, usize) {
    if count == 0 {
        return (0, 0);
    }
    let cols = (count as f32).sqrt().ceil() as usize;
    ((cols.max(1)), (count.div_ceil(cols.max(1))).max(1))
}

// ---------------------------------------------------------------------------
// Build statistics
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, Default)]
pub(crate) struct BuildStats {
    pub static_vertices: usize,
    pub prop_vertices: usize,
    pub prop_draws: usize,
    pub prop_models: usize,
    pub build_millis: f64,
    /// First (cold) build of the run, including any one-time prop model parse.
    pub cold_millis: f64,
    pub bake_millis: f64,
    pub estimate_vertices: u64,
    pub floor_vertices: usize,
    pub ceiling_vertices: usize,
    pub wall_vertices: usize,
    pub light_vertices: usize,
}

impl BuildStats {
    pub fn static_vbo_bytes(&self) -> usize {
        self.static_vertices * std::mem::size_of::<crate::render::Vertex>()
    }

    pub fn prop_vbo_bytes(&self) -> usize {
        self.prop_vertices * std::mem::size_of::<crate::render::Vertex>()
    }
}

fn batch_len(_mesh: &LevelMesh, batch: crate::render::BatchRange) -> usize {
    batch.count.max(0) as usize
}

/// Builds a level with real prop assets when available and records everything
/// the performance audit needs. `repeat` runs the build multiple times so a
/// release benchmark can report the best (least noisy) time.
pub(crate) fn measure(
    level: &LevelDef,
    catalog: &crate::loader::PropCatalog,
    assets: &mut crate::props::PropAssets,
    repeat: usize,
) -> (BuildStats, LevelMesh, Vec<PropMeshBatch>) {
    let mut best_total = f64::MAX;
    let mut cold_total = f64::MAX;
    let mut best_bake = f64::MAX;
    let mut mesh = None;
    let mut batches = None;
    let estimate = level.estimate_geometry();
    for round in 0..repeat.max(1) {
        let bake_started = Instant::now();
        let _lighting = LevelLighting::bake(level);
        best_bake = best_bake.min(bake_started.elapsed().as_secs_f64() * 1000.0);
        let mut local_assets = std::mem::take(assets);
        let started = Instant::now();
        let (built, prop_batches) =
            build_level_geometry_with_assets(level, catalog, &mut local_assets);
        let elapsed = started.elapsed().as_secs_f64() * 1000.0;
        best_total = best_total.min(elapsed);
        if round == 0 {
            cold_total = elapsed;
        }
        *assets = local_assets;
        mesh = Some(built);
        batches = Some(prop_batches);
    }
    let mesh = mesh.expect("at least one build");
    let batches = batches.expect("at least one build");
    let stats = BuildStats {
        static_vertices: mesh.vertices.len(),
        prop_vertices: batches.iter().map(|batch| batch.vertices.len()).sum(),
        prop_draws: batches.len(),
        prop_models: batches.len(),
        build_millis: best_total,
        cold_millis: cold_total,
        bake_millis: best_bake,
        estimate_vertices: estimate.total_vertices,
        floor_vertices: batch_len(&mesh, mesh.batches.floor_batch),
        ceiling_vertices: batch_len(&mesh, mesh.batches.ceiling_batch),
        wall_vertices: batch_len(&mesh, mesh.batches.wall_batch),
        light_vertices: batch_len(&mesh, mesh.batches.light_batch),
    };
    (stats, mesh, batches)
}

/// Every generated vertex colour must be finite and inside the renderer range.
pub(crate) fn assert_vertex_colors_safe(vertices: &[crate::render::Vertex]) {
    for (index, vertex) in vertices.iter().enumerate() {
        for (channel, value) in vertex.color.iter().enumerate() {
            assert!(
                value.is_finite(),
                "vertex {index} colour channel {channel} is not finite: {value}"
            );
            assert!(
                (0.0..=1.0).contains(value),
                "vertex {index} colour channel {channel} is outside [0, 1]: {value}"
            );
        }
        for (axis, value) in vertex.pos.iter().enumerate() {
            assert!(
                value.is_finite(),
                "vertex {index} position axis {axis} is not finite: {value}"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Benchmark levels
// ---------------------------------------------------------------------------

/// Level A: one small room, one fixture, a few props.
fn bench_tiny() -> LevelDef {
    parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "bench_tiny",
            "name": "Bench Tiny",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{}],
            "ceiling_lights": [{}],
            "props": [
                {{ "model": "core:chair", "x": 2.0, "z": 2.0 }},
                {{ "model": "core:crate", "x": 4.0, "z": 3.0 }},
                {{ "model": "core:plant", "x": 1.0, "z": 4.0 }}
            ]
        }}"#,
        room(0.0, 0.0, 6.0, 6.0, 3.0),
        light(3.0, 3.0, None),
    ))
}

/// Level D: one room with many fixtures, exercising the per-vertex light loop.
fn bench_many_lights(count: usize) -> LevelDef {
    parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "bench_many_lights",
            "name": "Bench Many Lights",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{}],
            "ceiling_lights": [{}]
        }}"#,
        room(0.0, 0.0, 40.0, 40.0, 3.5),
        (0..count)
            .map(|index| {
                let x = 2.0 + (index % 10) as f32 * 4.0;
                let z = 2.0 + (index / 10) as f32 * 4.0;
                light(x, z, None)
            })
            .collect::<Vec<_>>()
            .join(",")
    ))
}

/// Level E: few rooms with very large surfaces.
fn bench_large_surfaces() -> LevelDef {
    parse(&level_json(
        &format!(
            "{},{}",
            room(0.0, 0.0, 120.0, 120.0, 3.5),
            room(120.0, 0.0, 120.0, 120.0, 3.5)
        ),
        &(0..16)
            .map(|index| {
                let x = 10.0 + (index % 4) as f32 * 30.0;
                let z = 10.0 + (index / 4) as f32 * 30.0;
                light(x, z, None)
            })
            .collect::<Vec<_>>()
            .join(","),
    ))
}

/// Level F: many small rooms in a grid, each with two fixtures, joined by
/// doorways in their shared walls.
fn bench_many_rooms(grid: usize) -> LevelDef {
    let room_size = 8.0;
    let mut rooms = Vec::new();
    let mut lights = Vec::new();
    let mut walls = Vec::new();
    for row in 0..grid {
        for col in 0..grid {
            let x = col as f32 * room_size;
            let z = row as f32 * room_size;
            rooms.push(room(x, z, room_size, room_size, 3.0));
            lights.push(light(x + 2.5, z + 2.5, None));
            lights.push(light(x + 5.5, z + 5.5, None));
            // A doorway in the east wall of each room (interior walls only).
            if col + 1 < grid {
                walls.push(format!(
                    r#"{{ "x": {}, "z": {}, "width": 0.4, "depth": {}, "height": 3.0, "openings": [{{ "kind": "door", "offset": 3.0, "width": 1.2, "height": 2.1, "sill": 0.0 }}] }}"#,
                    x + room_size,
                    z,
                    room_size
                ));
            }
            if row + 1 < grid {
                walls.push(format!(
                    r#"{{ "x": {}, "z": {}, "width": {}, "depth": 0.4, "height": 3.0, "openings": [{{ "kind": "door", "offset": 3.0, "width": 1.2, "height": 2.1, "sill": 0.0 }}] }}"#,
                    x,
                    z + room_size,
                    room_size
                ));
            }
        }
    }
    parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "bench_many_rooms",
            "name": "Bench Many Rooms",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{}],
            "walls": [{}],
            "ceiling_lights": [{}]
        }}"#,
        rooms.join(","),
        walls.join(","),
        lights.join(",")
    ))
}

/// Level G: one room with many repeated props across several models.
fn bench_prop_heavy() -> LevelDef {
    let models = [
        "core:chair",
        "core:crate",
        "core:table",
        "core:lamp",
        "core:plant",
    ];
    let mut props = Vec::new();
    for index in 0..150 {
        let model = models[index % models.len()];
        let x = -14.0 + (index % 15) as f32 * 2.0;
        let z = -14.0 + (index / 15) as f32 * 2.6;
        props.push(format!(r#"{{ "model": "{model}", "x": {x}, "z": {z} }}"#));
    }
    parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "bench_prop_heavy",
            "name": "Bench Prop Heavy",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{}],
            "ceiling_lights": [{}],
            "props": [{}]
        }}"#,
        room(0.0, 0.0, 30.0, 30.0, 3.0),
        (0..6)
            .map(|index| light(4.0 + index as f32 * 4.4, 15.0, None))
            .collect::<Vec<_>>()
            .join(","),
        props.join(",")
    ))
}

/// Level H: the worst *reasonable* community level: a 5x5 room block with two
/// fixtures per room, doorways between neighbours and a moderate prop load.
fn bench_worst_reasonable() -> LevelDef {
    let grid = 5usize;
    let room_size = 14.0;
    let mut rooms = Vec::new();
    let mut lights = Vec::new();
    let mut walls = Vec::new();
    let mut props = Vec::new();
    for row in 0..grid {
        for col in 0..grid {
            let x = col as f32 * room_size;
            let z = row as f32 * room_size;
            rooms.push(room(x, z, room_size, room_size, 3.2));
            lights.push(light(x + 4.5, z + 4.5, None));
            lights.push(light(x + 9.5, z + 9.5, None));
            if col + 1 < grid {
                walls.push(format!(
                    r#"{{ "x": {}, "z": {}, "width": 0.4, "depth": {}, "height": 3.2, "openings": [{{ "kind": "door", "offset": 6.0, "width": 1.2, "height": 2.1, "sill": 0.0 }}] }}"#,
                    x + room_size,
                    z,
                    room_size
                ));
            }
            if row + 1 < grid {
                walls.push(format!(
                    r#"{{ "x": {}, "z": {}, "width": {}, "depth": 0.4, "height": 3.2, "openings": [{{ "kind": "door", "offset": 6.0, "width": 1.2, "height": 2.1, "sill": 0.0 }}] }}"#,
                    x,
                    z + room_size,
                    room_size
                ));
            }
            let models = ["core:chair", "core:table", "core:plant"];
            for index in 0..2 {
                let model = models[(row + col + index) % models.len()];
                props.push(format!(
                    r#"{{ "model": "{model}", "x": {}, "z": {} }}"#,
                    x + 3.0 + index as f32 * 6.0,
                    z + 3.0
                ));
            }
        }
    }
    parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "bench_worst_reasonable",
            "name": "Bench Worst Reasonable",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{}],
            "walls": [{}],
            "ceiling_lights": [{}],
            "props": [{}]
        }}"#,
        rooms.join(","),
        walls.join(","),
        lights.join(","),
        props.join(",")
    ))
}

fn shipped_level(name: &str) -> LevelDef {
    let path = format!("assets/levels/{name}.json");
    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{path} must be readable: {error}"));
    parse(&content)
}

fn demo_level() -> LevelDef {
    let path = "levels/asset_demo.json";
    let content = std::fs::read_to_string(path)
        .unwrap_or_else(|error| panic!("{path} must be readable: {error}"));
    parse(&content)
}

fn shipped_catalog() -> crate::loader::PropCatalog {
    let catalog = crate::loader::PropCatalog::load_default();
    assert!(
        catalog.contains("core:chair"),
        "the shipped prop catalogue must load for the audit"
    );
    catalog
}

fn shipped_assets() -> crate::props::PropAssets {
    let assets = crate::props::PropAssets::load_default();
    assert!(assets.root().is_some(), "assets/props must exist");
    assets
}

// ---------------------------------------------------------------------------
// Aggregate counters so a benchmark run can report lighting work honestly
// ---------------------------------------------------------------------------

/// Number of light/vertex candidate evaluations the naive all-lights loop would
/// perform for `points`. Used to quantify the effect of spatial pruning; not
/// part of the renderer.
#[allow(dead_code)]
pub(crate) fn count_light_evaluations(lighting: &LevelLighting, points: &[[f32; 3]]) -> u64 {
    let lights = lighting.lights().len() as u64;
    points.len() as u64 * lights
}

// ---------------------------------------------------------------------------
// Benchmark report
// ---------------------------------------------------------------------------

struct Row {
    name: &'static str,
    level: LevelDef,
    stats: BuildStats,
    rooms: usize,
    lights: usize,
    openings: usize,
    props: usize,
}

fn openings_of(level: &LevelDef) -> usize {
    level.walls.iter().map(|wall| wall.openings.len()).sum()
}

#[test]
fn lighting_benchmark_report() {
    let catalog = shipped_catalog();
    let mut assets = shipped_assets();
    let repeat = if cfg!(debug_assertions) { 1 } else { 3 };

    let mut rows: Vec<Row> = Vec::new();
    let mut add = |name: &'static str, level: LevelDef, assets: &mut crate::props::PropAssets| {
        let (stats, mesh, batches) = measure(&level, &catalog, assets, repeat);
        assert_vertex_colors_safe(&mesh.vertices);
        for batch in &batches {
            assert_vertex_colors_safe(&batch.vertices);
        }
        assert!(
            stats.static_vertices <= MAX_LEVEL_VERTICES as usize,
            "{name}: static geometry exceeds the level budget"
        );
        rows.push(Row {
            name,
            stats,
            rooms: level.room_iter().count(),
            lights: level.ceiling_lights.len(),
            openings: openings_of(&level),
            props: level.props.len(),
            level,
        });
    };

    add("A Tiny", bench_tiny(), &mut assets);
    add("B Asset Demo", demo_level(), &mut assets);
    add("C Level 1", shipped_level("level1"), &mut assets);
    add("D 100 lights", bench_many_lights(100), &mut assets);
    add("E Large surfaces", bench_large_surfaces(), &mut assets);
    add("F 36 rooms", bench_many_rooms(6), &mut assets);
    add("G Prop heavy", bench_prop_heavy(), &mut assets);
    add("H Worst reasonable", bench_worst_reasonable(), &mut assets);

    println!();
    println!(
        "{:<20} {:>5} {:>6} {:>7} {:>8} {:>9} {:>8} {:>7} {:>8} {:>10} {:>10} {:>10} {:>9}",
        "level",
        "rooms",
        "lights",
        "opens",
        "props",
        "static V",
        "prop V",
        "draws",
        "models",
        "build ms",
        "cold ms",
        "bake ms",
        "est V"
    );
    for row in &rows {
        let stats = row.stats;
        println!(
            "{:<20} {:>5} {:>6} {:>7} {:>8} {:>9} {:>8} {:>7} {:>8} {:>10.2} {:>10.2} {:>10.2} {:>9}",
            row.name,
            row.rooms,
            row.lights,
            row.openings,
            row.props,
            stats.static_vertices,
            stats.prop_vertices,
            stats.prop_draws,
            stats.prop_models,
            stats.build_millis,
            stats.cold_millis,
            stats.bake_millis,
            stats.estimate_vertices
        );
    }
    println!();
    println!(
        "{:<20} {:>10} {:>10} {:>10} {:>10} {:>10} {:>10}",
        "level", "floor V", "ceiling V", "wall V", "light V", "static KiB", "prop KiB"
    );
    for row in &rows {
        let stats = row.stats;
        println!(
            "{:<20} {:>10} {:>10} {:>10} {:>10} {:>10} {:>10}",
            row.name,
            stats.floor_vertices,
            stats.ceiling_vertices,
            stats.wall_vertices,
            stats.light_vertices,
            stats.static_vbo_bytes() / 1024,
            stats.prop_vbo_bytes() / 1024
        );
    }
    println!();

    // Budget arithmetic must actually bound the geometry that is generated.
    for row in &rows {
        let estimate = row.level.estimate_geometry();
        assert!(
            row.stats.static_vertices as u64 <= estimate.total_vertices,
            "{}: estimate {} does not bound the built {} static vertices",
            row.name,
            estimate.total_vertices,
            row.stats.static_vertices
        );
    }

    // The prop expansion stays inside the documented prop budget.
    let demo_stats = rows
        .iter()
        .find(|row| row.name == "B Asset Demo")
        .expect("demo row")
        .stats;
    assert!(demo_stats.prop_vertices <= MAX_LEVEL_PROP_VERTICES);

    // A dense synthetic prop level still batches into one draw per model.
    let prop_row = rows
        .iter()
        .find(|row| row.name == "G Prop heavy")
        .expect("prop-heavy row")
        .stats;
    assert!(
        prop_row.prop_draws <= 5,
        "150 props across five models must stay five draw calls, got {}",
        prop_row.prop_draws
    );
    assert!(prop_row.prop_draws > 0);
}

// ---------------------------------------------------------------------------
// Budget arithmetic
// ---------------------------------------------------------------------------

/// A wall gap, for building opening-heavy walls without repeating JSON.
fn opening(offset: f32, width: f32, height: f32) -> String {
    format!(
        r#"{{ "kind": "door", "offset": {offset}, "width": {width}, "height": {height}, "sill": 0.0 }}"#
    )
}

/// One long wall pierced by `count` evenly spaced doorways, in a long room.
#[allow(dead_code)]
fn opening_heavy_level(count: usize) -> LevelDef {
    let length = count as f32 * 3.0 + 3.0;
    let openings: Vec<String> = (0..count)
        .map(|index| opening(1.0 + index as f32 * 3.0, 1.0, 2.1))
        .collect();
    parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "openings",
            "name": "Openings",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{}],
            "walls": [{{
                "x": -0.2, "z": 0.0, "width": 0.4, "depth": {length},
                "height": 3.0, "openings": [{}]
            }}],
            "ceiling_lights": [{}]
        }}"#,
        room(-0.2, -1.0, length + 0.4, 20.0, 3.0),
        openings.join(","),
        light(length * 0.5, 9.0, None),
    ))
}

#[test]
fn budget_estimate_bounds_generated_geometry_for_opening_heavy_walls() {
    // The geometry estimate is the level's memory guardrail, so it must never
    // undercount what the builder emits, even for a wall with many openings.
    for (length, count) in [
        (10.0_f32, 0usize),
        (100.0, 0),
        (100.0, 1),
        (100.0, 3),
        (100.0, 32),
        (303.0, 100),
    ] {
        let openings: Vec<String> = (0..count)
            .map(|index| {
                opening(
                    length * (index as f32 + 1.0) / (count as f32 + 1.0),
                    1.0,
                    2.1,
                )
            })
            .collect();
        let level = parse(&format!(
            r#"{{
                "format_version": 1,
                "id": "openings",
                "name": "Openings",
                "spawn": {{ "x": 0.0, "z": 0.0 }},
                "rooms": [{}],
                "walls": [{{ "x": -0.2, "z": 0.0, "width": 0.4, "depth": {length}, "height": 3.0,
                             "openings": [{}] }}],
                "ceiling_lights": [{}]
            }}"#,
            room(-0.2, -1.0, length + 0.4, 20.0, 3.0),
            openings.join(","),
            light(length * 0.5, 9.0, None),
        ));
        let estimate = level.estimate_geometry();
        let mesh = build_level_geometry(&level);
        assert!(
            mesh.vertices.len() as u64 <= estimate.total_vertices,
            "length {length} with {count} openings: built {} static vertices but the estimate says {}",
            mesh.vertices.len(),
            estimate.total_vertices
        );
        assert!(
            mesh.batches.wall_batch.count as u64 <= estimate.wall_quads.saturating_mul(6),
            "length {length} with {count} openings: built {} wall vertices but the wall estimate says {}",
            mesh.batches.wall_batch.count,
            estimate.wall_quads * 6
        );
        assert!(estimate.total_vertices <= MAX_LEVEL_VERTICES);
    }
    // The same must hold for many walls with many openings each.
    let mut walls = Vec::new();
    for index in 0..40 {
        let openings: Vec<String> = (0..10)
            .map(|slot| opening(1.0 + slot as f32 * 2.0, 1.0, 2.1))
            .collect();
        walls.push(format!(
            r#"{{ "x": {}, "z": 0.0, "width": 0.3, "depth": 21.0, "height": 3.0, "openings": [{}] }}"#,
            index as f32 * 22.0,
            openings.join(",")
        ));
    }
    let level = parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "wall_forest",
            "name": "Wall Forest",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{}],
            "walls": [{}],
            "ceiling_lights": []
        }}"#,
        room(-1.0, -1.0, 900.0, 25.0, 3.0),
        walls.join(","),
    ));
    let estimate = level.estimate_geometry();
    let mesh = build_level_geometry(&level);
    assert!(
        mesh.vertices.len() as u64 <= estimate.total_vertices,
        "wall forest: built {} but estimated {}",
        mesh.vertices.len(),
        estimate.total_vertices
    );
}

#[test]
fn budget_estimate_is_tight_enough_to_not_over_reserve_wildly() {
    // The estimate is also the reservation size, so a representative level must
    // not over-reserve by an order of magnitude.
    let level = shipped_level("level1");
    let estimate = level.estimate_geometry();
    let mesh = build_level_geometry(&level);
    assert!(
        estimate.total_vertices >= mesh.vertices.len() as u64,
        "estimate must bound the build"
    );
    let ratio = estimate.total_vertices as f64 / mesh.vertices.len() as f64;
    assert!(
        ratio < 1.6,
        "level 1 estimate {ratio:.2}x the real geometry is too loose"
    );

    let demo = demo_level();
    let estimate = demo.estimate_geometry();
    let mesh = build_level_geometry(&demo);
    let ratio = estimate.total_vertices as f64 / mesh.vertices.len() as f64;
    assert!(
        ratio < 4.0,
        "asset demo estimate {ratio:.2}x the placeholder geometry is too loose"
    );
}

// ---------------------------------------------------------------------------
// Draw-call shape and batching (Phase 8)
// ---------------------------------------------------------------------------

#[test]
fn draw_calls_do_not_scale_with_fixture_count_and_batching_is_stable() {
    // One room, one chair: one static batch set plus one prop draw. Raising the
    // fixture count may grow the fixture vertex batch but must never add a draw
    // call, split a prop batch or reorder the static batches.
    let catalog = shipped_catalog();
    let mut assets = shipped_assets();
    let mut previous_shape = None;
    for count in [1usize, 4, 16, 64] {
        let level = parse(&format!(
            r#"{{
                "format_version": 1,
                "id": "draws",
                "name": "Draws",
                "spawn": {{ "x": 0.0, "z": 0.0 }},
                "rooms": [{}],
                "ceiling_lights": [{}],
                "props": [{{ "model": "core:chair", "x": 3.0, "z": 3.0 }}]
            }}"#,
            room(0.0, 0.0, 20.0, 20.0, 3.2),
            (0..count)
                .map(|index| light(
                    2.0 + (index % 4) as f32 * 5.0,
                    2.0 + (index / 4) as f32 * 5.0,
                    None
                ))
                .collect::<Vec<_>>()
                .join(","),
        ));
        let (mesh, batches) = build_level_geometry_with_assets(&level, &catalog, &mut assets);
        assert_eq!(batches.len(), 1, "{count} lights: one prop model, one draw");
        let shape = (
            mesh.batches.floor_batch.count > 0,
            mesh.batches.ceiling_batch.count > 0,
            mesh.batches.wall_batch.count > 0,
            mesh.batches.light_batch.count > 0,
            mesh.batches.prop_batch.count > 0,
            batches.len(),
        );
        if let Some(previous) = previous_shape {
            assert_eq!(
                shape, previous,
                "{count} lights changed the draw-call shape"
            );
        }
        previous_shape = Some(shape);
        assert_eq!(mesh.batches.light_batch.count, count as i32 * 18);
    }
}

#[test]
fn ten_chairs_in_different_lighting_stay_one_batch() {
    let catalog = shipped_catalog();
    let mut assets = shipped_assets();
    // Spread ten chairs from directly under a fixture to a dark corner.
    let mut props = Vec::new();
    for index in 0..10 {
        props.push(format!(
            r#"{{ "model": "core:chair", "x": {}, "z": {} }}"#,
            1.5 + index as f32 * 1.8,
            1.5 + index as f32 * 1.8
        ));
    }
    let level = parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "ten_chairs",
            "name": "Ten Chairs",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{}],
            "ceiling_lights": [{}],
            "props": [{}]
        }}"#,
        room(0.0, 0.0, 22.0, 22.0, 3.0),
        light(2.0, 2.0, None),
        props.join(","),
    ));
    let (_, batches) = build_level_geometry_with_assets(&level, &catalog, &mut assets);
    assert_eq!(batches.len(), 1, "ten chairs must stay one model batch");
    let single = {
        let one = parse(&format!(
            r#"{{
                "format_version": 1, "id": "one", "name": "One", "spawn": {{ "x": 0.0, "z": 0.0 }},
                "rooms": [{}], "ceiling_lights": [{}],
                "props": [{{ "model": "core:chair", "x": 1.5, "z": 1.5 }}]
            }}"#,
            room(0.0, 0.0, 22.0, 22.0, 3.0),
            light(2.0, 2.0, None),
        ));
        let (_, batches) = build_level_geometry_with_assets(&one, &catalog, &mut assets);
        batches[0].vertices.len()
    };
    assert_eq!(batches[0].vertices.len(), single * 10);

    // Different lighting per instance survives inside the shared batch.
    let luminance: Vec<f32> = batches[0]
        .vertices
        .chunks(single)
        .map(|instance| {
            instance
                .iter()
                .map(|vertex| vertex.color[0])
                .fold(0.0_f32, f32::max)
        })
        .collect();
    let brightest = luminance.iter().cloned().fold(0.0_f32, f32::max);
    let dimmest = luminance.iter().cloned().fold(f32::MAX, f32::min);
    assert!(
        brightest > dimmest + 0.05,
        "per-instance lighting must vary inside one batch: {luminance:?}"
    );
}

// ---------------------------------------------------------------------------
// Determinism (Group R) and deterministic fuzz-style stress (Phase 10)
// ---------------------------------------------------------------------------

#[test]
fn group_r_repeated_builds_are_bit_identical() {
    let levels = [
        shipped_level("level1"),
        demo_level(),
        bench_many_rooms(4),
        bench_worst_reasonable(),
        bench_many_lights(64),
    ];
    for (index, level) in levels.iter().enumerate() {
        let first = build_level_geometry(level);
        let second = build_level_geometry(level);
        assert_eq!(
            first.vertices.len(),
            second.vertices.len(),
            "level {index}: vertex count drifted"
        );
        for (a, b) in first.vertices.iter().zip(second.vertices.iter()) {
            assert_eq!(a.pos, b.pos, "level {index}: position drifted");
            assert_eq!(a.color, b.color, "level {index}: colour drifted");
            assert_eq!(a.uv, b.uv, "level {index}: uv drifted");
        }
        assert_eq!(
            first.batches, second.batches,
            "level {index}: batches drifted"
        );
        assert_eq!(
            level.estimate_geometry(),
            level.estimate_geometry(),
            "level {index}: estimate is not deterministic"
        );

        let a = LevelLighting::bake(level);
        let b = LevelLighting::bake(level);
        assert_eq!(a.rooms(), b.rooms(), "level {index}: baselines drifted");
        assert_eq!(a.lights(), b.lights(), "level {index}: fixtures drifted");
        assert_eq!(a.summary(), b.summary());
    }
}

/// Tiny deterministic LCG so the stress test uses no external dependency.
struct Lcg(u64);

impl Lcg {
    fn next_u32(&mut self) -> u32 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        (self.0 >> 33) as u32
    }

    fn unit(&mut self) -> f32 {
        self.next_u32() as f32 / u32::MAX as f32
    }

    fn range(&mut self, low: f32, high: f32) -> f32 {
        low + (high - low) * self.unit()
    }

    fn int(&mut self, low: i32, high: i32) -> i32 {
        low + (self.next_u32() % ((high - low + 1) as u32)) as i32
    }
}

#[test]
fn deterministic_fuzz_levels_bake_and_build_within_budget() {
    // 48 pseudo-random but valid levels: overlapping rooms, mixed ceiling
    // heights, fixture grids, openings, props and odd rotations. Fixed seed, so
    // a failure reproduces exactly.
    let catalog = shipped_catalog();
    let mut assets = shipped_assets();
    let models = [
        "core:chair",
        "core:crate",
        "core:plant",
        "core:table",
        "spooner-man",
    ];
    let mut rng = Lcg(0x5eed_1234_abcd_0001);
    for case in 0..48 {
        let room_count = rng.int(1, 4) as usize;
        let mut rooms = Vec::new();
        for _ in 0..room_count {
            let w = rng.range(2.0, 40.0);
            let d = rng.range(2.0, 40.0);
            let h = rng.range(2.0, 6.0);
            let x = rng.range(-10.0, 10.0);
            let z = rng.range(-10.0, 10.0);
            rooms.push(room(x, z, w, d, h));
        }
        let light_count = rng.int(0, 12) as usize;
        let mut lights = Vec::new();
        for _ in 0..light_count {
            let x = rng.range(-10.0, 30.0);
            let z = rng.range(-10.0, 30.0);
            let intensity = rng.range(0.0, 2.5);
            lights.push(light(x, z, Some(intensity)));
        }
        let prop_count = rng.int(0, 12) as usize;
        let mut props = Vec::new();
        for _ in 0..prop_count {
            let model = models[(rng.next_u32() as usize) % models.len()];
            let x = rng.range(-12.0, 30.0);
            let y = rng.range(-0.3, 2.5);
            let z = rng.range(-12.0, 30.0);
            let rotation = rng.range(0.0, 360.0);
            props.push(format!(
                r#"{{ "model": "{model}", "x": {x}, "y": {y}, "z": {z}, "rotation_degrees": {rotation} }}"#
            ));
        }
        let wall_count = rng.int(0, 6) as usize;
        let mut walls = Vec::new();
        for _ in 0..wall_count {
            let x = rng.range(-12.0, 28.0);
            let z = rng.range(-12.0, 28.0);
            let w = rng.range(1.0, 20.0);
            let d = rng.range(0.3, 0.6);
            let openings = if rng.unit() < 0.5 {
                format!(
                    r#"[{{ "kind": "door", "offset": 0.5, "width": {}, "height": 2.1, "sill": 0.0 }}]"#,
                    rng.range(0.8, (w - 1.0).max(0.9))
                )
            } else {
                "[]".to_string()
            };
            walls.push(format!(
                r#"{{ "x": {x}, "z": {z}, "width": {w}, "depth": {d}, "height": 3.0, "openings": {openings} }}"#
            ));
        }

        let json = format!(
            r#"{{
                "format_version": 1,
                "id": "fuzz_{case}",
                "name": "Fuzz {case}",
                "spawn": {{ "x": 0.0, "z": 0.0 }},
                "rooms": [{}],
                "walls": [{}],
                "ceiling_lights": [{}],
                "props": [{}]
            }}"#,
            rooms.join(","),
            walls.join(","),
            lights.join(","),
            props.join(",")
        );
        let level = parse(&json);
        // Validation may reject the odd random level (enormous total area);
        // anything it accepts must bake and build safely.
        if crate::loader::validate_level(&level).is_err() {
            continue;
        }
        let lighting = LevelLighting::bake(&level);
        for info in lighting.rooms() {
            assert!(info.baseline.is_finite());
            assert!((0.55..=1.0).contains(&info.baseline));
        }
        let (mesh, batches) = build_level_geometry_with_assets(&level, &catalog, &mut assets);
        assert_vertex_colors_safe(&mesh.vertices);
        for batch in &batches {
            assert_vertex_colors_safe(&batch.vertices);
        }
        assert!(mesh.vertices.len() as u64 <= level.estimate_geometry().total_vertices);
        assert!(
            mesh.vertices.len() as u64
                + batches.iter().map(|b| b.vertices.len() as u64).sum::<u64>()
                <= MAX_LEVEL_VERTICES + MAX_LEVEL_PROP_VERTICES as u64
        );

        // A handful of representative sample points per level.
        for _ in 0..12 {
            let x = rng.range(-15.0, 35.0);
            let y = rng.range(-1.0, 6.0);
            let z = rng.range(-15.0, 35.0);
            let value = lighting.sample(x, y, z);
            assert!(value.is_finite(), "case {case}: sample ({x}, {y}, {z})");
            assert!((0.55..=1.0).contains(&value));
        }
    }
}

// ---------------------------------------------------------------------------
// Regression tests for audited lighting bugs
// ---------------------------------------------------------------------------

/// Two rooms sharing a wall, one bright and one dim, with a configurable wall.
fn shared_wall_level(wall_y: f32, opening_sill: f32, opening_width: f32) -> LevelDef {
    parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "shared",
            "name": "Shared",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{},{}],
            "walls": [{{
                "x": 10.0, "y": {wall_y}, "z": 0.0, "width": 0.4, "depth": 10.0, "height": 3.0,
                "openings": [{{ "kind": "door", "offset": 4.5, "width": {opening_width}, "height": 2.1, "sill": {opening_sill} }}]
            }}],
            "ceiling_lights": [{},{},{},{},{},{},{}]
        }}"#,
        room(0.0, 0.0, 10.0, 10.0, 3.0),
        room(10.4, 0.0, 20.0, 10.0, 3.0),
        light(2.0, 2.0, None),
        light(5.0, 2.0, None),
        light(8.0, 2.0, None),
        light(2.0, 8.0, None),
        light(5.0, 8.0, None),
        light(8.0, 8.0, None),
        light(20.0, 5.0, None),
    ))
}

#[test]
fn regression_raised_walls_do_not_blend_through_their_openings() {
    let sample_at = |level: &LevelDef, x: f32, y: f32, z: f32| {
        LevelLighting::bake(level).sample_in_room(1, x, y, z)
    };
    let solid_control = |mut level: LevelDef| {
        level.walls[0].openings.clear();
        level
    };

    // A walk-through doorway at floor level blends...
    let floor_wall = LevelLighting::bake(&shared_wall_level(0.0, 0.0, 1.0));
    assert!(floor_wall.rooms()[1].baseline < floor_wall.rooms()[0].baseline);
    let blended = sample_at(&shared_wall_level(0.0, 0.0, 1.0), 10.5, 0.0, 5.0);
    let floor_solid = sample_at(
        &solid_control(shared_wall_level(0.0, 0.0, 1.0)),
        10.5,
        0.0,
        5.0,
    );
    assert!(
        blended > floor_solid + 0.01,
        "a floor-level doorway must blend: {blended} vs solid {floor_solid}"
    );

    // ...but the same opening in a wall raised to 2.5 m is a hole near the
    // ceiling, not a passage: no light may leak through it.
    let raised = sample_at(&shared_wall_level(2.5, 0.0, 1.0), 10.5, 0.0, 5.0);
    let raised_solid = sample_at(
        &solid_control(shared_wall_level(2.5, 0.0, 1.0)),
        10.5,
        0.0,
        5.0,
    );
    assert!(
        (raised - raised_solid).abs() < 1e-5,
        "a raised wall's opening must not blend: {raised} vs solid {raised_solid}"
    );
    // Even at the opening's own height nothing leaks.
    let at_opening_height = sample_at(&shared_wall_level(2.5, 0.0, 1.0), 10.5, 2.7, 5.0);
    let height_solid = sample_at(
        &solid_control(shared_wall_level(2.5, 0.0, 1.0)),
        10.5,
        2.7,
        5.0,
    );
    assert!((at_opening_height - height_solid).abs() < 1e-5);

    // A sill above the floor on a grounded wall is a window, not a door.
    let window = sample_at(&shared_wall_level(0.0, 0.5, 1.0), 10.5, 0.0, 5.0);
    let window_solid = sample_at(
        &solid_control(shared_wall_level(0.0, 0.5, 1.0)),
        10.5,
        0.0,
        5.0,
    );
    assert!((window - window_solid).abs() < 1e-5);
}

#[test]
fn regression_invalid_openings_do_not_create_phantom_doorways() {
    let solid = LevelLighting::bake(&shared_wall_level(0.0, 0.0, 1.0));
    // Programmatic malformations that validation would normally reject: none
    // may blend, so the bake must match a wall with no opening at all.
    let reference = {
        let mut level = shared_wall_level(0.0, 0.0, 1.0);
        level.walls[0].openings.clear();
        LevelLighting::bake(&level)
    };
    let reference_sample = reference.sample_in_room(1, 10.5, 0.0, 5.0);
    for (label, mutate) in [
        (
            "zero width",
            (|o: &mut crate::level::WallOpeningDef| o.width = 0.0)
                as fn(&mut crate::level::WallOpeningDef),
        ),
        ("negative width", |o| o.width = -1.0),
        ("zero height", |o| o.height = 0.0),
        ("NaN height", |o| o.height = f32::NAN),
        ("infinite height", |o| o.height = f32::INFINITY),
        ("NaN sill", |o| o.sill = f32::NAN),
        ("non-finite offset", |o| o.offset = f32::INFINITY),
    ] {
        let mut level = shared_wall_level(0.0, 0.0, 1.0);
        mutate(&mut level.walls[0].openings[0]);
        let lighting = LevelLighting::bake(&level);
        assert_eq!(
            lighting.rooms(),
            reference.rooms(),
            "{label}: open malformed opening changed the bake"
        );
        let value = lighting.sample_in_room(1, 10.5, 0.0, 5.0);
        assert!(
            (value - reference_sample).abs() < 1e-5,
            "{label}: phantom doorway leaked light ({value} vs {reference_sample})"
        );
    }
    // The malformed wall still builds without panicking.
    let mut level = shared_wall_level(0.0, 0.0, 1.0);
    level.walls[0].openings[0].width = f32::NAN;
    assert_vertex_colors_safe(&build_level_geometry(&level).vertices);
    let _ = solid;
}

#[test]
fn regression_fractional_rotations_agree_between_bake_and_panel_geometry() {
    use crate::lighting::fixture_half_extents;
    for rotation in [
        0.0_f32, 45.0, 89.6, 90.0, 135.0, 179.0, 179.6, 180.0, 180.4, 270.0, 360.0, -90.0, -0.6,
    ] {
        let (half_w, half_d) = fixture_half_extents(rotation);
        let level = parse(&format!(
            r#"{{
                "format_version": 1,
                "id": "rotation",
                "name": "Rotation",
                "spawn": {{ "x": 0.0, "z": 0.0 }},
                "rooms": [{}],
                "ceiling_lights": [{{ "fixture": "core:fluorescent_panel_01", "x": 5.0, "z": 5.0,
                                      "rotation_degrees": {rotation} }}]
            }}"#,
            room(0.0, 0.0, 10.0, 10.0, 3.0),
        ));
        let lighting = LevelLighting::bake(&level);
        assert_eq!(lighting.lights()[0].half_w, half_w, "rotation {rotation}");
        assert_eq!(lighting.lights()[0].half_d, half_d, "rotation {rotation}");

        // The drawn fixture panel must have the same footprint as the pool.
        let mesh = build_level_geometry(&level);
        let fixture = &mesh.vertices[mesh.batches.light_batch.start as usize
            ..(mesh.batches.light_batch.start + mesh.batches.light_batch.count) as usize];
        let mut min_x = f32::MAX;
        let mut max_x = f32::MIN;
        let mut min_z = f32::MAX;
        let mut max_z = f32::MIN;
        for vertex in fixture {
            min_x = min_x.min(vertex.pos[0]);
            max_x = max_x.max(vertex.pos[0]);
            min_z = min_z.min(vertex.pos[2]);
            max_z = max_z.max(vertex.pos[2]);
        }
        // The panel is the widest quad; the bezels add 0.05 m on each side of
        // both axes, so the batch bounds are the panel extents plus 0.1 m.
        assert!(
            ((max_x - min_x) - (half_w * 2.0 + 0.1)).abs() < 1e-5,
            "rotation {rotation}: drawn x extent {} vs pool {}",
            max_x - min_x,
            half_w * 2.0 + 0.1
        );
        assert!(
            ((max_z - min_z) - (half_d * 2.0 + 0.1)).abs() < 1e-5,
            "rotation {rotation}: drawn z extent {} vs pool {}",
            max_z - min_z,
            half_d * 2.0 + 0.1
        );
    }
}

#[test]
fn regression_wall_reveals_take_light_from_both_rooms() {
    // A doorway between a bright and a dim room: the jamb reveal is a quad
    // spanning the wall thickness, and its four corners must carry the light of
    // the room each edge faces instead of the ambient value of the wall cavity.
    let level = shared_wall_level(0.0, 0.0, 1.0);
    let lighting = LevelLighting::bake(&level);
    let bright = lighting.rooms()[0].baseline;
    let dim = lighting.rooms()[1].baseline;
    assert!(bright > dim + 0.05);

    let mesh = build_level_geometry(&level);
    let walls = &mesh.vertices[mesh.batches.wall_batch.start as usize
        ..(mesh.batches.wall_batch.start + mesh.batches.wall_batch.count) as usize];
    // The reveal quads sit at the door's jamb boundaries (z = 4.5 and z = 5.5)
    // and span the wall thickness in X, carrying each face's room light.
    let jamb_bright: Vec<f32> = walls
        .iter()
        .filter(|v| {
            (v.pos[0] - 10.0).abs() < 1e-4
                && ((v.pos[2] - 4.5).abs() < 1e-4 || (v.pos[2] - 5.5).abs() < 1e-4)
        })
        .map(|v| v.color[0])
        .collect();
    let jamb_dim: Vec<f32> = walls
        .iter()
        .filter(|v| {
            (v.pos[0] - 10.4).abs() < 1e-4
                && ((v.pos[2] - 4.5).abs() < 1e-4 || (v.pos[2] - 5.5).abs() < 1e-4)
        })
        .map(|v| v.color[0])
        .collect();
    assert!(!jamb_bright.is_empty() && !jamb_dim.is_empty());
    let max_bright = jamb_bright.iter().cloned().fold(0.0_f32, f32::max);
    let min_dim = jamb_dim.iter().cloned().fold(f32::MAX, f32::min);
    // The bright-side edge reads brighter than the dim-side edge, and neither
    // collapsed to the ambient value of the wall cavity.
    assert!(
        max_bright > min_dim + 0.02,
        "jamb edges must track the rooms they face: {max_bright} vs {min_dim}"
    );
    assert!(
        max_bright > crate::lighting::MIN_AMBIENT + 0.01,
        "the bright jamb edge must carry room light, got {max_bright}"
    );
    assert_vertex_colors_safe(walls);
}

// ---------------------------------------------------------------------------
// Tessellation audit: merging must be lossless at the sampling positions
// ---------------------------------------------------------------------------

/// Extracts the four corners and colours of every quad in a vertex slice.
///
/// `add_quad` emits `p0, p1, p2, p0, p2, p3`, so the quad corners are indices
/// 0, 1, 2 and 5.
#[allow(clippy::type_complexity, clippy::chunks_exact_to_as_chunks)]
fn quads(vertices: &[crate::render::Vertex]) -> Vec<([(f32, f32); 4], [[f32; 4]; 4])> {
    assert_eq!(vertices.len() % 6, 0, "batches must be whole quads");
    vertices
        .chunks_exact(6)
        .map(|quad| {
            let corner = |index: usize| (quad[index].pos[0], quad[index].pos[2]);
            let color = |index: usize| quad[index].color;
            (
                [corner(0), corner(1), corner(2), corner(5)],
                [color(0), color(1), color(2), color(5)],
            )
        })
        .collect()
}

#[test]
fn merged_floor_and_ceiling_quads_keep_exact_samples_and_tile_the_room() {
    for level in [shipped_level("level1"), demo_level()] {
        let lighting = LevelLighting::bake(&level);
        let mesh = build_level_geometry(&level);
        let floor = &mesh.vertices[mesh.batches.floor_batch.start as usize
            ..(mesh.batches.floor_batch.start + mesh.batches.floor_batch.count) as usize];
        let ceiling = &mesh.vertices[mesh.batches.ceiling_batch.start as usize
            ..(mesh.batches.ceiling_batch.start + mesh.batches.ceiling_batch.count) as usize];
        assert_vertex_colors_safe(floor);
        assert_vertex_colors_safe(ceiling);

        // Every surviving corner keeps the exact sample it was given: find a
        // room that contains the corner and matches the baked colour.
        let matches_floor = |x: f32, z: f32, color: [f32; 4]| {
            (0..lighting.rooms().len()).any(|room| {
                let expected = lighting.sample_in_room(room, x, 0.0, z);
                (0..3).all(|channel| (color[channel] - expected).abs() < 1e-6)
            })
        };
        let matches_ceiling = |x: f32, z: f32, color: [f32; 4]| {
            lighting.rooms().iter().enumerate().any(|(room, info)| {
                let expected = lighting.sample_in_room(room, x, info.height_m, z);
                let expected = [0.72 * expected, 0.72 * expected, 0.70 * expected];
                (0..3).all(|channel| (color[channel] - expected[channel]).abs() < 1e-6)
            })
        };
        for quad in quads(floor) {
            for index in 0..4 {
                let (x, z) = quad.0[index];
                assert!(
                    matches_floor(x, z, quad.1[index]),
                    "floor corner ({x}, {z}) colour {:?} does not match any room bake",
                    quad.1[index]
                );
            }
        }
        for quad in quads(ceiling) {
            for index in 0..4 {
                let (x, z) = quad.0[index];
                assert!(
                    matches_ceiling(x, z, quad.1[index]),
                    "ceiling corner ({x}, {z}) colour {:?} does not match any room bake",
                    quad.1[index]
                );
            }
        }

        // Coverage: the emitted floor quads tile each room exactly, so no hole
        // or overlap was introduced by merging.
        for room in level.room_iter() {
            let x0 = room.x.min(room.x + room.width);
            let x1 = room.x.max(room.x + room.width);
            let area = (x1 - x0) * room.depth;
            let mut covered = 0.0_f64;
            for (corners, _) in quads(floor) {
                // Shoelace area of the quad (axis-aligned rectangles here).
                let mut twice = 0.0_f64;
                for index in 0..4 {
                    let (ax, az) = corners[index];
                    let (bx, bz) = corners[(index + 1) % 4];
                    twice += ax as f64 * bz as f64 - bx as f64 * az as f64;
                }
                let center_x = corners.iter().map(|c| c.0).sum::<f32>() / 4.0;
                let center_z = corners.iter().map(|c| c.1).sum::<f32>() / 4.0;
                if center_x > x0
                    && center_x < x1
                    && center_z > room.z
                    && center_z < room.z + room.depth
                {
                    covered += twice.abs() * 0.5;
                }
            }
            assert!(
                (covered - area as f64).abs() < (area as f64) * 0.01 + 1e-3,
                "room floor coverage {covered} vs area {area}"
            );
        }
    }
}

#[test]
fn merged_wall_strips_share_exact_edges() {
    // A long lit corridor wall: consecutive wall quads on the same face must
    // meet with identical colours at their shared boundary (the cached corner
    // sample), so merging cannot introduce a seam.
    let wall_lights = format!("{},{}", light(4.0, 4.0, None), light(20.0, 4.0, None));
    let level = parse(&format!(
        r#"{{
            "format_version": 1,
            "id": "wall_edges",
            "name": "Wall Edges",
            "spawn": {{ "x": 0.0, "z": 0.0 }},
            "rooms": [{}],
            "walls": [{{ "x": -0.4, "z": -0.2, "width": 0.4, "depth": 24.0, "height": 3.0 }}],
            "ceiling_lights": [{wall_lights}]
        }}"#,
        room(-0.4, -0.2, 24.4, 8.0, 3.0),
    ));
    let mesh = build_level_geometry(&level);
    let wall = &mesh.vertices[mesh.batches.wall_batch.start as usize
        ..(mesh.batches.wall_batch.start + mesh.batches.wall_batch.count) as usize];

    // Group vertices by the world coordinate across the wall's thickness
    // (x = -0.4 is one face, x = 0.0 the other) and by height; within a face,
    // the colour as a function of position must be single-valued. The wall's
    // end caps (z at the wall ends) deliberately use a different face tint, so
    // they are excluded.
    let mut samples: std::collections::HashMap<(i32, i32, i32), [f32; 4]> =
        std::collections::HashMap::new();
    for vertex in wall {
        if (vertex.pos[2] + 0.2).abs() < 1e-4 || (vertex.pos[2] - 23.8).abs() < 1e-4 {
            continue;
        }
        let key = (
            (vertex.pos[0] * 1000.0).round() as i32,
            (vertex.pos[1] * 1000.0).round() as i32,
            (vertex.pos[2] * 1000.0).round() as i32,
        );
        match samples.get(&key) {
            Some(existing) => assert_eq!(
                *existing, vertex.color,
                "same wall position {key:?} carries two different colours"
            ),
            None => {
                samples.insert(key, vertex.color);
            }
        }
    }
    assert!(samples.len() > 8, "the wall must emit real geometry");
}
