//! External (PNG-backed) decal sheets.
//!
//! The four built-in decal sheets are generated by the renderer; a decal asset
//! with `source: "file"` and a `.png` model is ordinary external artwork like a
//! surface texture, resolved through the same catalog and decoded once per
//! session into the same cache.

use std::path::Path;
use std::rc::Rc;

use crate::assets::AssetCatalog;

use super::image::{RawImage, TextureCache, load_png_relative};

/// One external (PNG-backed) decal sheet a level places.
///
/// The four built-in decal sheets are generated by the renderer; a decal asset
/// with `source: "file"` and a `.png` model is ordinary external artwork like a
/// surface texture, resolved through the same catalog and decoded once per
/// session into the same [`TextureCache`].
#[derive(Clone, Debug)]
pub struct ResolvedDecalSheet {
    /// Logical decal asset id, exactly as the level writes it.
    pub material: String,
    /// Texture cache key (the PNG path relative to the asset root).
    pub key: String,
    /// Decoded pixels, shared with the session cache.
    pub image: Rc<RawImage>,
}

/// Resolves one decal sheet asset to its decoded PNG.
///
/// # Errors
///
/// Returns a message naming the decal and the exact catalog/PNG problem when
/// the asset is unknown, is not a `file` decal with a `.png` model, the asset
/// root is missing, or the PNG cannot be decoded.
pub fn resolve_decal_sheet(
    catalog: &AssetCatalog,
    asset_root: Option<&Path>,
    cache: &mut TextureCache,
    material_id: &str,
) -> Result<ResolvedDecalSheet, String> {
    let Some(entry) = catalog.get(material_id) else {
        return Err(format!(
            "decal `{material_id}` is not declared in the asset catalog"
        ));
    };
    if !matches!(entry.source, crate::assets::AssetSource::File) {
        return Err(format!(
            "decal `{material_id}` is not a file asset; a generated decal is drawn from the built-in sheet"
        ));
    }
    let Some(path) = entry.model.as_deref() else {
        return Err(format!(
            "decal `{material_id}` names no PNG; a file-backed decal needs a `model`"
        ));
    };
    if !path.to_ascii_lowercase().ends_with(".png") {
        return Err(format!(
            "decal `{material_id}` must name a `.png` sheet, found `{path}`"
        ));
    }
    let key = path.to_string();
    if let Some(image) = cache.get(&key) {
        return Ok(ResolvedDecalSheet {
            material: material_id.to_string(),
            key,
            image,
        });
    }
    let Some(root) = asset_root else {
        return Err(format!("decal `{material_id}`: the asset root is missing"));
    };
    let image =
        load_png_relative(root, &key).map_err(|error| format!("decal `{material_id}`: {error}"))?;
    let image = cache.insert(key.clone(), image);
    Ok(ResolvedDecalSheet {
        material: material_id.to_string(),
        key,
        image,
    })
}
