manifest_version = 1
name = "Places"
id = "io.vitrallis.liminalrust"
version = "0.11.1"
runtime = "rust"

[binaries]
armv7-unknown-linux-gnueabihf = "bin/armv7-unknown-linux-gnueabihf/app"

[permissions]
network = false
audio = false
storage = true
